// Code generated by protoc-gen-go. DO NOT EDIT.
// source: TileService.proto

package Cw_TileService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Row Request
type TileType int32

const (
	TileType_ImageTile     TileType = 0
	TileType_VideoTile     TileType = 1
	TileType_FeatureTile   TileType = 2
	TileType_AdvertiseTile TileType = 3
	TileType_CarouselTile  TileType = 4
)

var TileType_name = map[int32]string{
	0: "ImageTile",
	1: "VideoTile",
	2: "FeatureTile",
	3: "AdvertiseTile",
	4: "CarouselTile",
}

var TileType_value = map[string]int32{
	"ImageTile":     0,
	"VideoTile":     1,
	"FeatureTile":   2,
	"AdvertiseTile": 3,
	"CarouselTile":  4,
}

func (x TileType) String() string {
	return proto.EnumName(TileType_name, int32(x))
}

func (TileType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{0}
}

type RowLayout int32

const (
	RowLayout_Landscape RowLayout = 0
	RowLayout_Portrait  RowLayout = 1
	RowLayout_Square    RowLayout = 3
	RowLayout_Circle    RowLayout = 4
)

var RowLayout_name = map[int32]string{
	0: "Landscape",
	1: "Portrait",
	3: "Square",
	4: "Circle",
}

var RowLayout_value = map[string]int32{
	"Landscape": 0,
	"Portrait":  1,
	"Square":    3,
	"Circle":    4,
}

func (x RowLayout) String() string {
	return proto.EnumName(RowLayout_name, int32(x))
}

func (RowLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{1}
}

type RowType int32

const (
	RowType_Editorial      RowType = 0
	RowType_Recommendation RowType = 1
	RowType_Dynamic        RowType = 2
)

var RowType_name = map[int32]string{
	0: "Editorial",
	1: "Recommendation",
	2: "Dynamic",
}

var RowType_value = map[string]int32{
	"Editorial":      0,
	"Recommendation": 1,
	"Dynamic":        2,
}

func (x RowType) String() string {
	return proto.EnumName(RowType_name, int32(x))
}

func (RowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{2}
}

// Prime Pages
type CloudwalkerSchedule struct {
	Pages                []*Page  `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CloudwalkerSchedule) Reset()         { *m = CloudwalkerSchedule{} }
func (m *CloudwalkerSchedule) String() string { return proto.CompactTextString(m) }
func (*CloudwalkerSchedule) ProtoMessage()    {}
func (*CloudwalkerSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{0}
}

func (m *CloudwalkerSchedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloudwalkerSchedule.Unmarshal(m, b)
}
func (m *CloudwalkerSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloudwalkerSchedule.Marshal(b, m, deterministic)
}
func (m *CloudwalkerSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloudwalkerSchedule.Merge(m, src)
}
func (m *CloudwalkerSchedule) XXX_Size() int {
	return xxx_messageInfo_CloudwalkerSchedule.Size(m)
}
func (m *CloudwalkerSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_CloudwalkerSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_CloudwalkerSchedule proto.InternalMessageInfo

func (m *CloudwalkerSchedule) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

type Page struct {
	PageName             string   `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageEndpoint         string   `protobuf:"bytes,2,opt,name=pageEndpoint,proto3" json:"pageEndpoint,omitempty"`
	PageIndex            int32    `protobuf:"varint,3,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *Page) GetPageEndpoint() string {
	if m != nil {
		return m.PageEndpoint
	}
	return ""
}

func (m *Page) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

type PrimePagesRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PrimePagesRequest) Reset()         { *m = PrimePagesRequest{} }
func (m *PrimePagesRequest) String() string { return proto.CompactTextString(m) }
func (*PrimePagesRequest) ProtoMessage()    {}
func (*PrimePagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{2}
}

func (m *PrimePagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimePagesRequest.Unmarshal(m, b)
}
func (m *PrimePagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimePagesRequest.Marshal(b, m, deterministic)
}
func (m *PrimePagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimePagesRequest.Merge(m, src)
}
func (m *PrimePagesRequest) XXX_Size() int {
	return xxx_messageInfo_PrimePagesRequest.Size(m)
}
func (m *PrimePagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimePagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimePagesRequest proto.InternalMessageInfo

func (m *PrimePagesRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *PrimePagesRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

// Pages Request
type PageRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	PageName             string   `protobuf:"bytes,3,opt,name=pageName,proto3" json:"pageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PageRequest) Reset()         { *m = PageRequest{} }
func (m *PageRequest) String() string { return proto.CompactTextString(m) }
func (*PageRequest) ProtoMessage()    {}
func (*PageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{3}
}

func (m *PageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageRequest.Unmarshal(m, b)
}
func (m *PageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageRequest.Marshal(b, m, deterministic)
}
func (m *PageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageRequest.Merge(m, src)
}
func (m *PageRequest) XXX_Size() int {
	return xxx_messageInfo_PageRequest.Size(m)
}
func (m *PageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PageRequest proto.InternalMessageInfo

func (m *PageRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *PageRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *PageRequest) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

type PageResponse struct {
	CarouselEndpoint     string   `protobuf:"bytes,1,opt,name=carouselEndpoint,proto3" json:"carouselEndpoint,omitempty"`
	RowContentEndpoint   []string `protobuf:"bytes,2,rep,name=rowContentEndpoint,proto3" json:"rowContentEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PageResponse) Reset()         { *m = PageResponse{} }
func (m *PageResponse) String() string { return proto.CompactTextString(m) }
func (*PageResponse) ProtoMessage()    {}
func (*PageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{4}
}

func (m *PageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageResponse.Unmarshal(m, b)
}
func (m *PageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageResponse.Marshal(b, m, deterministic)
}
func (m *PageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageResponse.Merge(m, src)
}
func (m *PageResponse) XXX_Size() int {
	return xxx_messageInfo_PageResponse.Size(m)
}
func (m *PageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PageResponse proto.InternalMessageInfo

func (m *PageResponse) GetCarouselEndpoint() string {
	if m != nil {
		return m.CarouselEndpoint
	}
	return ""
}

func (m *PageResponse) GetRowContentEndpoint() []string {
	if m != nil {
		return m.RowContentEndpoint
	}
	return nil
}

// Carousel Request
type CarouselRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	PageName             string   `protobuf:"bytes,3,opt,name=pageName,proto3" json:"pageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *CarouselRequest) Reset()         { *m = CarouselRequest{} }
func (m *CarouselRequest) String() string { return proto.CompactTextString(m) }
func (*CarouselRequest) ProtoMessage()    {}
func (*CarouselRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{5}
}

func (m *CarouselRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarouselRequest.Unmarshal(m, b)
}
func (m *CarouselRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarouselRequest.Marshal(b, m, deterministic)
}
func (m *CarouselRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarouselRequest.Merge(m, src)
}
func (m *CarouselRequest) XXX_Size() int {
	return xxx_messageInfo_CarouselRequest.Size(m)
}
func (m *CarouselRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CarouselRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CarouselRequest proto.InternalMessageInfo

func (m *CarouselRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *CarouselRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *CarouselRequest) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

type CarouselResponse struct {
	Carousel             []*Carousel `protobuf:"bytes,1,rep,name=carousel,proto3" json:"carousel,omitempty"`
	CarouselBaseUrl      string      `protobuf:"bytes,2,opt,name=carouselBaseUrl,proto3" json:"carouselBaseUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-" bson:"-"`
	XXX_unrecognized     []byte      `json:"-" bson:"-"`
	XXX_sizecache        int32       `json:"-" bson:"-"`
}

func (m *CarouselResponse) Reset()         { *m = CarouselResponse{} }
func (m *CarouselResponse) String() string { return proto.CompactTextString(m) }
func (*CarouselResponse) ProtoMessage()    {}
func (*CarouselResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{6}
}

func (m *CarouselResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CarouselResponse.Unmarshal(m, b)
}
func (m *CarouselResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CarouselResponse.Marshal(b, m, deterministic)
}
func (m *CarouselResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CarouselResponse.Merge(m, src)
}
func (m *CarouselResponse) XXX_Size() int {
	return xxx_messageInfo_CarouselResponse.Size(m)
}
func (m *CarouselResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CarouselResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CarouselResponse proto.InternalMessageInfo

func (m *CarouselResponse) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *CarouselResponse) GetCarouselBaseUrl() string {
	if m != nil {
		return m.CarouselBaseUrl
	}
	return ""
}

type Carousel struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PackageName          string   `protobuf:"bytes,4,opt,name=packageName,proto3" json:"packageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{7}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Carousel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type ContentTile struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	MediaUrl             string   `protobuf:"bytes,2,opt,name=mediaUrl,proto3" json:"mediaUrl,omitempty"`
	TileType             TileType `protobuf:"varint,3,opt,name=tileType,proto3,enum=Cw_TileService.TileType" json:"tileType,omitempty"`
	Poster               string   `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	Portrait             string   `protobuf:"bytes,5,opt,name=portrait,proto3" json:"portrait,omitempty"`
	IsDetailPage         bool     `protobuf:"varint,6,opt,name=isDetailPage,proto3" json:"isDetailPage,omitempty"`
	PackageName          string   `protobuf:"bytes,7,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ContentId            string   `protobuf:"bytes,8,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Target               []string `protobuf:"bytes,9,rep,name=target,proto3" json:"target,omitempty"`
	RealeaseDate         string   `protobuf:"bytes,10,opt,name=realeaseDate,proto3" json:"realeaseDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *ContentTile) Reset()         { *m = ContentTile{} }
func (m *ContentTile) String() string { return proto.CompactTextString(m) }
func (*ContentTile) ProtoMessage()    {}
func (*ContentTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{8}
}

func (m *ContentTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentTile.Unmarshal(m, b)
}
func (m *ContentTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentTile.Marshal(b, m, deterministic)
}
func (m *ContentTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentTile.Merge(m, src)
}
func (m *ContentTile) XXX_Size() int {
	return xxx_messageInfo_ContentTile.Size(m)
}
func (m *ContentTile) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentTile.DiscardUnknown(m)
}

var xxx_messageInfo_ContentTile proto.InternalMessageInfo

func (m *ContentTile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ContentTile) GetMediaUrl() string {
	if m != nil {
		return m.MediaUrl
	}
	return ""
}

func (m *ContentTile) GetTileType() TileType {
	if m != nil {
		return m.TileType
	}
	return TileType_ImageTile
}

func (m *ContentTile) GetPoster() string {
	if m != nil {
		return m.Poster
	}
	return ""
}

func (m *ContentTile) GetPortrait() string {
	if m != nil {
		return m.Portrait
	}
	return ""
}

func (m *ContentTile) GetIsDetailPage() bool {
	if m != nil {
		return m.IsDetailPage
	}
	return false
}

func (m *ContentTile) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *ContentTile) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentTile) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *ContentTile) GetRealeaseDate() string {
	if m != nil {
		return m.RealeaseDate
	}
	return ""
}

type RowRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	PageName             string   `protobuf:"bytes,3,opt,name=pageName,proto3" json:"pageName,omitempty"`
	RowName              string   `protobuf:"bytes,4,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowType              string   `protobuf:"bytes,5,opt,name=rowType,proto3" json:"rowType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RowRequest) Reset()         { *m = RowRequest{} }
func (m *RowRequest) String() string { return proto.CompactTextString(m) }
func (*RowRequest) ProtoMessage()    {}
func (*RowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{9}
}

func (m *RowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowRequest.Unmarshal(m, b)
}
func (m *RowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowRequest.Marshal(b, m, deterministic)
}
func (m *RowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowRequest.Merge(m, src)
}
func (m *RowRequest) XXX_Size() int {
	return xxx_messageInfo_RowRequest.Size(m)
}
func (m *RowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RowRequest proto.InternalMessageInfo

func (m *RowRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *RowRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *RowRequest) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *RowRequest) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *RowRequest) GetRowType() string {
	if m != nil {
		return m.RowType
	}
	return ""
}

type InterRowResponse struct {
	RowName              string    `protobuf:"bytes,1,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowLayout            RowLayout `protobuf:"varint,2,opt,name=rowLayout,proto3,enum=Cw_TileService.RowLayout" json:"rowLayout,omitempty"`
	ContentBaseUrl       string    `protobuf:"bytes,3,opt,name=contentBaseUrl,proto3" json:"contentBaseUrl,omitempty"`
	ContentId            string    `protobuf:"bytes,4,opt,name=contentId,proto3" json:"contentId,omitempty"`
	Shuffle              bool      `protobuf:"varint,5,opt,name=shuffle,proto3" json:"shuffle,omitempty"`
	RowIndex             int32     `protobuf:"varint,6,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-" bson:"-"`
	XXX_unrecognized     []byte    `json:"-" bson:"-"`
	XXX_sizecache        int32     `json:"-" bson:"-"`
}

func (m *InterRowResponse) Reset()         { *m = InterRowResponse{} }
func (m *InterRowResponse) String() string { return proto.CompactTextString(m) }
func (*InterRowResponse) ProtoMessage()    {}
func (*InterRowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{10}
}

func (m *InterRowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterRowResponse.Unmarshal(m, b)
}
func (m *InterRowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterRowResponse.Marshal(b, m, deterministic)
}
func (m *InterRowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterRowResponse.Merge(m, src)
}
func (m *InterRowResponse) XXX_Size() int {
	return xxx_messageInfo_InterRowResponse.Size(m)
}
func (m *InterRowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InterRowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InterRowResponse proto.InternalMessageInfo

func (m *InterRowResponse) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *InterRowResponse) GetRowLayout() RowLayout {
	if m != nil {
		return m.RowLayout
	}
	return RowLayout_Landscape
}

func (m *InterRowResponse) GetContentBaseUrl() string {
	if m != nil {
		return m.ContentBaseUrl
	}
	return ""
}

func (m *InterRowResponse) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *InterRowResponse) GetShuffle() bool {
	if m != nil {
		return m.Shuffle
	}
	return false
}

func (m *InterRowResponse) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

type RowResponse struct {
	RowName              string         `protobuf:"bytes,1,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowLayout            RowLayout      `protobuf:"varint,2,opt,name=rowLayout,proto3,enum=Cw_TileService.RowLayout" json:"rowLayout,omitempty"`
	ContentBaseUrl       string         `protobuf:"bytes,3,opt,name=contentBaseUrl,proto3" json:"contentBaseUrl,omitempty"`
	ContentTiles         []*ContentTile `protobuf:"bytes,4,rep,name=contentTiles,proto3" json:"contentTiles,omitempty"`
	RowIndex             int32          `protobuf:"varint,5,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-" bson:"-"`
	XXX_unrecognized     []byte         `json:"-" bson:"-"`
	XXX_sizecache        int32          `json:"-" bson:"-"`
}

func (m *RowResponse) Reset()         { *m = RowResponse{} }
func (m *RowResponse) String() string { return proto.CompactTextString(m) }
func (*RowResponse) ProtoMessage()    {}
func (*RowResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_28928c4b0d64237b, []int{11}
}

func (m *RowResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowResponse.Unmarshal(m, b)
}
func (m *RowResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowResponse.Marshal(b, m, deterministic)
}
func (m *RowResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowResponse.Merge(m, src)
}
func (m *RowResponse) XXX_Size() int {
	return xxx_messageInfo_RowResponse.Size(m)
}
func (m *RowResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RowResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RowResponse proto.InternalMessageInfo

func (m *RowResponse) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *RowResponse) GetRowLayout() RowLayout {
	if m != nil {
		return m.RowLayout
	}
	return RowLayout_Landscape
}

func (m *RowResponse) GetContentBaseUrl() string {
	if m != nil {
		return m.ContentBaseUrl
	}
	return ""
}

func (m *RowResponse) GetContentTiles() []*ContentTile {
	if m != nil {
		return m.ContentTiles
	}
	return nil
}

func (m *RowResponse) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func init() {
	proto.RegisterEnum("Cw_TileService.TileType", TileType_name, TileType_value)
	proto.RegisterEnum("Cw_TileService.RowLayout", RowLayout_name, RowLayout_value)
	proto.RegisterEnum("Cw_TileService.RowType", RowType_name, RowType_value)
	proto.RegisterType((*CloudwalkerSchedule)(nil), "Cw_TileService.CloudwalkerSchedule")
	proto.RegisterType((*Page)(nil), "Cw_TileService.Page")
	proto.RegisterType((*PrimePagesRequest)(nil), "Cw_TileService.PrimePagesRequest")
	proto.RegisterType((*PageRequest)(nil), "Cw_TileService.PageRequest")
	proto.RegisterType((*PageResponse)(nil), "Cw_TileService.PageResponse")
	proto.RegisterType((*CarouselRequest)(nil), "Cw_TileService.CarouselRequest")
	proto.RegisterType((*CarouselResponse)(nil), "Cw_TileService.CarouselResponse")
	proto.RegisterType((*Carousel)(nil), "Cw_TileService.Carousel")
	proto.RegisterType((*ContentTile)(nil), "Cw_TileService.ContentTile")
	proto.RegisterType((*RowRequest)(nil), "Cw_TileService.RowRequest")
	proto.RegisterType((*InterRowResponse)(nil), "Cw_TileService.InterRowResponse")
	proto.RegisterType((*RowResponse)(nil), "Cw_TileService.RowResponse")
}

func init() { proto.RegisterFile("TileService.proto", fileDescriptor_28928c4b0d64237b) }

var fileDescriptor_28928c4b0d64237b = []byte{
	// 981 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xee, 0xc6, 0xff, 0xc7, 0xae, 0xe3, 0x0c, 0x05, 0x2d, 0x4e, 0x24, 0xdc, 0xad, 0xa0, 0x6e,
	0x24, 0xb2, 0x28, 0x54, 0xfc, 0x09, 0x89, 0x06, 0xa7, 0x44, 0x91, 0x2a, 0x14, 0x6d, 0x02, 0x5c,
	0x20, 0x81, 0xa6, 0xbb, 0xa7, 0xee, 0xd0, 0xf5, 0x8e, 0x3b, 0x3b, 0x8e, 0x89, 0xa2, 0x08, 0x89,
	0x3b, 0xb8, 0x42, 0xe2, 0x01, 0x78, 0x1e, 0xae, 0x79, 0x02, 0x24, 0x78, 0x0f, 0x34, 0x3f, 0xbb,
	0xde, 0xb5, 0x5d, 0x50, 0x51, 0x2f, 0x7a, 0xb7, 0xe7, 0x67, 0xce, 0x77, 0xbe, 0x33, 0xe7, 0xcc,
	0x59, 0xd8, 0x3a, 0x63, 0x31, 0x9e, 0xa2, 0x38, 0x67, 0x21, 0xee, 0x4d, 0x05, 0x97, 0x9c, 0x74,
	0x47, 0xf3, 0x6f, 0x0b, 0xda, 0xfe, 0xce, 0x98, 0xf3, 0x71, 0x8c, 0x3e, 0x9d, 0x32, 0x9f, 0x26,
	0x09, 0x97, 0x54, 0x32, 0x9e, 0xa4, 0xc6, 0xdb, 0x3b, 0x80, 0x57, 0x46, 0x31, 0x9f, 0x45, 0x73,
	0x1a, 0x3f, 0x41, 0x71, 0x1a, 0x3e, 0xc6, 0x68, 0x16, 0x23, 0xd9, 0x85, 0xda, 0x94, 0x8e, 0x31,
	0x75, 0x9d, 0x41, 0x65, 0xd8, 0xde, 0xbf, 0xb1, 0x57, 0x0e, 0xba, 0x77, 0x42, 0xc7, 0x18, 0x18,
	0x17, 0x2f, 0x82, 0xaa, 0x12, 0x49, 0x1f, 0x9a, 0x4a, 0xf1, 0x39, 0x9d, 0xa0, 0xeb, 0x0c, 0x9c,
	0x61, 0x2b, 0xc8, 0x65, 0xe2, 0x41, 0x47, 0x7d, 0xdf, 0x4f, 0xa2, 0x29, 0x67, 0x89, 0x74, 0x37,
	0xb4, 0xbd, 0xa4, 0x23, 0x3b, 0xd0, 0x52, 0xf2, 0x71, 0x12, 0xe1, 0xf7, 0x6e, 0x65, 0xe0, 0x0c,
	0x6b, 0xc1, 0x42, 0xe1, 0x1d, 0xc0, 0xd6, 0x89, 0x60, 0x13, 0x54, 0x50, 0x69, 0x80, 0x4f, 0x67,
	0x98, 0x4a, 0xf2, 0x1a, 0xd4, 0xcf, 0x31, 0x89, 0xb8, 0xb0, 0x80, 0x56, 0x22, 0x37, 0xa0, 0xf6,
	0x50, 0xd0, 0x24, 0xb2, 0x38, 0x46, 0xf0, 0xbe, 0x82, 0xb6, 0xce, 0xfb, 0xff, 0x1c, 0x2e, 0xb1,
	0xab, 0x94, 0xd9, 0x79, 0xdf, 0x41, 0xc7, 0x04, 0x4e, 0xa7, 0x3c, 0x49, 0x55, 0xf5, 0x7a, 0x21,
	0x15, 0x7c, 0x96, 0x62, 0x9c, 0x33, 0x36, 0x18, 0x2b, 0x7a, 0xb2, 0x07, 0x44, 0xf0, 0xf9, 0x88,
	0x27, 0x12, 0x13, 0x59, 0xa8, 0x4f, 0x65, 0xd8, 0x0a, 0xd6, 0x58, 0xbc, 0xaf, 0x61, 0x73, 0x64,
	0x63, 0xbc, 0x78, 0x22, 0x02, 0x7a, 0x8b, 0xe0, 0x96, 0xcc, 0x5d, 0x68, 0x66, 0x49, 0xdb, 0x6e,
	0x70, 0x97, 0xbb, 0x21, 0x3f, 0x93, 0x7b, 0x92, 0x21, 0x6c, 0x66, 0xdf, 0x9f, 0xd2, 0x14, 0xbf,
	0x10, 0xb1, 0xcd, 0x62, 0x59, 0xed, 0x9d, 0x43, 0x33, 0x3b, 0xaf, 0x72, 0x63, 0x13, 0x3a, 0xd6,
	0xee, 0xb6, 0x85, 0x32, 0x59, 0xb1, 0x94, 0x54, 0x8c, 0x31, 0x6b, 0x1e, 0x2b, 0x29, 0x96, 0x92,
	0xc9, 0x38, 0x23, 0x63, 0x04, 0x32, 0x80, 0xf6, 0x94, 0x86, 0x4f, 0x32, 0xa2, 0x55, 0x6d, 0x2b,
	0xaa, 0xbc, 0xdf, 0x37, 0xa0, 0x6d, 0x8b, 0xab, 0xb8, 0x2c, 0xe2, 0x38, 0xc5, 0x38, 0x7d, 0x68,
	0x4e, 0x30, 0x62, 0x74, 0x41, 0x20, 0x97, 0x55, 0x65, 0x24, 0x8b, 0xf1, 0xec, 0x62, 0x6a, 0xc0,
	0xbb, 0xab, 0x95, 0x39, 0xb3, 0xf6, 0x20, 0xf7, 0x54, 0x3c, 0xa6, 0x3c, 0x95, 0x28, 0x6c, 0x52,
	0x56, 0xd2, 0xf7, 0xc2, 0x85, 0x14, 0x94, 0x49, 0xb7, 0x66, 0xef, 0xc5, 0xca, 0x6a, 0x7c, 0x58,
	0x7a, 0x88, 0x92, 0xb2, 0x58, 0x35, 0x9a, 0x5b, 0x1f, 0x38, 0xc3, 0x66, 0x50, 0xd2, 0x2d, 0x33,
	0x6e, 0xac, 0x30, 0x56, 0x03, 0x16, 0x1a, 0xc2, 0xc7, 0x91, 0xdb, 0xd4, 0xf6, 0x85, 0xa2, 0x50,
	0xdf, 0x96, 0x6e, 0xbe, 0xac, 0xbe, 0x1e, 0x74, 0x04, 0xd2, 0x18, 0x69, 0x8a, 0x87, 0x54, 0xa2,
	0x0b, 0x66, 0x74, 0x8b, 0x3a, 0xef, 0x67, 0x07, 0x20, 0xe0, 0xf3, 0x17, 0xde, 0x90, 0xc4, 0x85,
	0x86, 0xe0, 0xf3, 0xc2, 0x15, 0x66, 0xa2, 0xb5, 0xe8, 0xda, 0xd7, 0x72, 0x8b, 0x12, 0xbd, 0x3f,
	0x1d, 0xe8, 0x1d, 0x27, 0x12, 0x85, 0xce, 0xc8, 0x76, 0x71, 0x21, 0x90, 0x53, 0x0e, 0xf4, 0x3e,
	0xb4, 0x04, 0x9f, 0x3f, 0xa0, 0x17, 0x7c, 0x66, 0x5a, 0xab, 0xbb, 0xff, 0xfa, 0xf2, 0x35, 0x06,
	0x99, 0x43, 0xb0, 0xf0, 0x25, 0x6f, 0x41, 0xd7, 0x56, 0x2f, 0xeb, 0x70, 0x93, 0xfd, 0x92, 0xb6,
	0x5c, 0xf6, 0xea, 0x72, 0xd9, 0x5d, 0x68, 0xa4, 0x8f, 0x67, 0x8f, 0x1e, 0xc5, 0x86, 0x47, 0x33,
	0xc8, 0x44, 0x55, 0x17, 0xc1, 0xe7, 0xe6, 0x39, 0xac, 0xeb, 0xe7, 0x30, 0x97, 0xbd, 0xbf, 0x1d,
	0x68, 0xbf, 0x24, 0xf4, 0x3e, 0x81, 0x4e, 0xb8, 0x18, 0xa3, 0xd4, 0xad, 0xea, 0x37, 0x62, 0x7b,
	0xe5, 0x8d, 0x58, 0xf8, 0x04, 0xa5, 0x03, 0x25, 0x9e, 0xb5, 0x32, 0xcf, 0xdd, 0x6f, 0xa0, 0x99,
	0x8d, 0x10, 0xb9, 0x0e, 0xad, 0x63, 0xf5, 0x18, 0x28, 0x45, 0xef, 0x9a, 0x12, 0xbf, 0x64, 0x11,
	0x72, 0x2d, 0x3a, 0x64, 0x13, 0xda, 0x9f, 0x21, 0x95, 0x33, 0x61, 0xec, 0x1b, 0x64, 0x0b, 0xae,
	0x1f, 0x44, 0xe7, 0x28, 0x24, 0x4b, 0x8d, 0xaa, 0x42, 0x7a, 0xd0, 0xc9, 0x9e, 0x1a, 0xad, 0xa9,
	0xee, 0xde, 0x83, 0x56, 0x4e, 0x5e, 0x45, 0x7c, 0x40, 0x93, 0x28, 0x0d, 0xe9, 0x54, 0x01, 0x74,
	0xa0, 0x79, 0x62, 0x07, 0xb0, 0xe7, 0x10, 0x80, 0xfa, 0xe9, 0xd3, 0x19, 0x15, 0x2a, 0x0e, 0x40,
	0x7d, 0xc4, 0x44, 0xa8, 0x23, 0x7c, 0x08, 0x8d, 0xc0, 0x34, 0x9e, 0x3a, 0x7f, 0x3f, 0x62, 0x92,
	0x0b, 0x46, 0xe3, 0xde, 0x35, 0x42, 0xa0, 0x1b, 0x60, 0xc8, 0x27, 0x13, 0x4c, 0x22, 0xbd, 0x73,
	0x7b, 0x0e, 0x69, 0x43, 0xe3, 0xf0, 0x22, 0xa1, 0x13, 0x16, 0xf6, 0x36, 0xf6, 0x7f, 0xab, 0x41,
	0xbb, 0x50, 0x22, 0xf2, 0x8b, 0x03, 0xaf, 0x16, 0x96, 0xf1, 0x62, 0xdd, 0x91, 0x9b, 0x2b, 0xfb,
	0x77, 0x79, 0x15, 0xf6, 0x6f, 0xad, 0x14, 0x7c, 0x75, 0xad, 0x7b, 0xfe, 0x8f, 0x7f, 0xfc, 0xf5,
	0xeb, 0xc6, 0x1d, 0x72, 0xdb, 0x0f, 0xd7, 0xe1, 0xf8, 0x97, 0x66, 0x50, 0xaf, 0xfc, 0x4b, 0x3d,
	0x9a, 0x57, 0x84, 0x43, 0xe3, 0x08, 0xa5, 0x7e, 0x5f, 0xb6, 0xd7, 0xfe, 0x03, 0x58, 0xf4, 0x9d,
	0xf5, 0x46, 0xd3, 0x9d, 0xde, 0x1d, 0x0d, 0x7b, 0x8b, 0xdc, 0xf4, 0xd5, 0x60, 0xaf, 0xa0, 0xf8,
	0x97, 0xd9, 0xbc, 0x5f, 0x91, 0x1f, 0xa0, 0x7d, 0x84, 0x32, 0x5f, 0x08, 0x6f, 0x3c, 0x73, 0xd5,
	0x58, 0xe0, 0xc1, 0xb3, 0x1d, 0x2c, 0xf8, 0xdb, 0x1a, 0xfc, 0x36, 0x79, 0xd3, 0xcf, 0x36, 0xcf,
	0x7f, 0x24, 0x50, 0x3f, 0x42, 0x19, 0xf0, 0x39, 0xe9, 0xaf, 0x19, 0x93, 0x0c, 0x76, 0x7b, 0xad,
	0xcd, 0x22, 0x7e, 0xac, 0x11, 0xdf, 0x23, 0x77, 0x7d, 0xc1, 0xe7, 0xff, 0x06, 0xe6, 0x5f, 0xda,
	0x29, 0x35, 0x5f, 0xaa, 0x89, 0xae, 0xc8, 0x4f, 0x0e, 0x80, 0x2a, 0x81, 0x19, 0x91, 0xe7, 0xcb,
	0xa2, 0x30, 0x64, 0xde, 0x3d, 0x9d, 0xc5, 0x47, 0xe4, 0x03, 0xdf, 0x4e, 0xdb, 0xf3, 0x66, 0xf2,
	0x8e, 0xf3, 0xb0, 0xae, 0x7f, 0x12, 0xdf, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x85, 0x4c, 0xfe,
	0xc2, 0x67, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TileServiceClient is the client API for TileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TileServiceClient interface {
	CloudwalkerPrimePages(ctx context.Context, in *PrimePagesRequest, opts ...grpc.CallOption) (*CloudwalkerSchedule, error)
	GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error)
	GetCarousel(ctx context.Context, in *CarouselRequest, opts ...grpc.CallOption) (*CarouselResponse, error)
	GetRow(ctx context.Context, in *RowRequest, opts ...grpc.CallOption) (*RowResponse, error)
	GetContent(ctx context.Context, in *RowRequest, opts ...grpc.CallOption) (TileService_GetContentClient, error)
}

type tileServiceClient struct {
	cc *grpc.ClientConn
}

func NewTileServiceClient(cc *grpc.ClientConn) TileServiceClient {
	return &tileServiceClient{cc}
}

func (c *tileServiceClient) CloudwalkerPrimePages(ctx context.Context, in *PrimePagesRequest, opts ...grpc.CallOption) (*CloudwalkerSchedule, error) {
	out := new(CloudwalkerSchedule)
	err := c.cc.Invoke(ctx, "/Cw_TileService.TileService/CloudwalkerPrimePages", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tileServiceClient) GetPage(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*PageResponse, error) {
	out := new(PageResponse)
	err := c.cc.Invoke(ctx, "/Cw_TileService.TileService/GetPage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tileServiceClient) GetCarousel(ctx context.Context, in *CarouselRequest, opts ...grpc.CallOption) (*CarouselResponse, error) {
	out := new(CarouselResponse)
	err := c.cc.Invoke(ctx, "/Cw_TileService.TileService/GetCarousel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tileServiceClient) GetRow(ctx context.Context, in *RowRequest, opts ...grpc.CallOption) (*RowResponse, error) {
	out := new(RowResponse)
	err := c.cc.Invoke(ctx, "/Cw_TileService.TileService/GetRow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tileServiceClient) GetContent(ctx context.Context, in *RowRequest, opts ...grpc.CallOption) (TileService_GetContentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TileService_serviceDesc.Streams[0], "/Cw_TileService.TileService/GetContent", opts...)
	if err != nil {
		return nil, err
	}
	x := &tileServiceGetContentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TileService_GetContentClient interface {
	Recv() (*ContentTile, error)
	grpc.ClientStream
}

type tileServiceGetContentClient struct {
	grpc.ClientStream
}

func (x *tileServiceGetContentClient) Recv() (*ContentTile, error) {
	m := new(ContentTile)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TileServiceServer is the server API for TileService service.
type TileServiceServer interface {
	CloudwalkerPrimePages(context.Context, *PrimePagesRequest) (*CloudwalkerSchedule, error)
	GetPage(context.Context, *PageRequest) (*PageResponse, error)
	GetCarousel(context.Context, *CarouselRequest) (*CarouselResponse, error)
	GetRow(context.Context, *RowRequest) (*RowResponse, error)
	GetContent(*RowRequest, TileService_GetContentServer) error
}

// UnimplementedTileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTileServiceServer struct {
}

func (*UnimplementedTileServiceServer) CloudwalkerPrimePages(ctx context.Context, req *PrimePagesRequest) (*CloudwalkerSchedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloudwalkerPrimePages not implemented")
}
func (*UnimplementedTileServiceServer) GetPage(ctx context.Context, req *PageRequest) (*PageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPage not implemented")
}
func (*UnimplementedTileServiceServer) GetCarousel(ctx context.Context, req *CarouselRequest) (*CarouselResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCarousel not implemented")
}
func (*UnimplementedTileServiceServer) GetRow(ctx context.Context, req *RowRequest) (*RowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRow not implemented")
}
func (*UnimplementedTileServiceServer) GetContent(req *RowRequest, srv TileService_GetContentServer) error {
	return status.Errorf(codes.Unimplemented, "method GetContent not implemented")
}

func RegisterTileServiceServer(s *grpc.Server, srv TileServiceServer) {
	s.RegisterService(&_TileService_serviceDesc, srv)
}

func _TileService_CloudwalkerPrimePages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimePagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TileServiceServer).CloudwalkerPrimePages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cw_TileService.TileService/CloudwalkerPrimePages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TileServiceServer).CloudwalkerPrimePages(ctx, req.(*PrimePagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TileService_GetPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TileServiceServer).GetPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cw_TileService.TileService/GetPage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TileServiceServer).GetPage(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TileService_GetCarousel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CarouselRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TileServiceServer).GetCarousel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cw_TileService.TileService/GetCarousel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TileServiceServer).GetCarousel(ctx, req.(*CarouselRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TileService_GetRow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TileServiceServer).GetRow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Cw_TileService.TileService/GetRow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TileServiceServer).GetRow(ctx, req.(*RowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TileService_GetContent_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TileServiceServer).GetContent(m, &tileServiceGetContentServer{stream})
}

type TileService_GetContentServer interface {
	Send(*ContentTile) error
	grpc.ServerStream
}

type tileServiceGetContentServer struct {
	grpc.ServerStream
}

func (x *tileServiceGetContentServer) Send(m *ContentTile) error {
	return x.ServerStream.SendMsg(m)
}

var _TileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Cw_TileService.TileService",
	HandlerType: (*TileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloudwalkerPrimePages",
			Handler:    _TileService_CloudwalkerPrimePages_Handler,
		},
		{
			MethodName: "GetPage",
			Handler:    _TileService_GetPage_Handler,
		},
		{
			MethodName: "GetCarousel",
			Handler:    _TileService_GetCarousel_Handler,
		},
		{
			MethodName: "GetRow",
			Handler:    _TileService_GetRow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetContent",
			Handler:       _TileService_GetContent_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "TileService.proto",
}
